version: '3'

services:
  rest-auth:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - DEBUG=True
    env_file:
      - .env